<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | Curated Avatar Catalog
    |--------------------------------------------------------------------------
    |
    | Each category maps to a subdirectory under public/avatars/curated/.
    | Each avatar key maps to a {name}.svg file in that subdirectory.
    | Add new packs (seasonal, themed) by adding new categories here and
    | dropping matching SVG files into the corresponding folder.
    |
    */

    'categories' => [

        'cozy_objects' => [
            'label'   => 'Cozy Objects',
            'avatars' => [
                'lantern'          => 'Lantern',
                'teacup'           => 'Tea Cup',
                'book_stack'       => 'Book Stack',
                'cassette'         => 'Cassette Tape',
                'candle'           => 'Candle',
                'headphones'       => 'Headphones',
                'warm_mug'         => 'Warm Mug',
                'typewriter'       => 'Typewriter',
                'desk_lamp'        => 'Desk Lamp',
                'hot_chocolate'    => 'Hot Chocolate',
                'journal'          => 'Journal',
                'record_player'    => 'Record Player',
                'rainy_window'     => 'Rainy Window',
                'tiny_radio'       => 'Tiny Radio',
                'instant_noodles'  => 'Instant Noodles',
                'aquarium_lamp'    => 'Aquarium Lamp',
                'blanket_fold'     => 'Blanket Fold',
                'yarn_ball'        => 'Yarn Ball',
                'plant_pot'        => 'Plant Pot',
                'snow_globe'       => 'Snow Globe',
                'film_camera'      => 'Film Camera',
                'letter_envelope'  => 'Letter & Envelope',
                'wind_chime'       => 'Wind Chime',
                'pocket_watch'     => 'Pocket Watch',
                'hot_water_bottle' => 'Hot Water Bottle',
                'incense'          => 'Incense',
                'vinyl_record'     => 'Vinyl Record',
                'matches'          => 'Matches',
                'tea_kettle'       => 'Tea Kettle',
                'cozy_corner'      => 'Cozy Corner',
            ],
        ],

        'nature' => [
            'label'   => 'Nature & Atmosphere',
            'avatars' => [
                'moon'           => 'Moon',
                'mushroom'       => 'Mushroom',
                'campfire'       => 'Campfire',
                'owl'            => 'Owl',
                'clouds'         => 'Clouds',
                'fireflies'      => 'Fireflies',
                'pine_forest'    => 'Pine Forest',
                'koi_fish'       => 'Koi Fish',
                'rain_cloud'     => 'Rain Cloud',
                'snowy_trees'    => 'Snowy Trees',
                'foggy_hills'    => 'Foggy Hills',
                'stars'          => 'Stars',
                'frog_lily'      => 'Frog on Lily',
                'mountain_dusk'  => 'Mountain Dusk',
                'thunderstorm'   => 'Thunderstorm',
                'aquarium_glow'  => 'Aquarium Glow',
                'sunset_clouds'  => 'Sunset Clouds',
                'quiet_ocean'    => 'Quiet Ocean',
                'snowflake'      => 'Snowflake',
                'river_stones'   => 'River Stones',
                'morning_mist'   => 'Morning Mist',
                'tide_pool'      => 'Tide Pool',
                'night_garden'   => 'Night Garden',
                'moss_stone'     => 'Moss Stone',
                'bird_on_wire'   => 'Bird on Wire',
                'dragonfly'      => 'Dragonfly',
                'rain_drops'     => 'Rain Drops',
                'autumn_leaves'  => 'Autumn Leaves',
                'spring_cherry'  => 'Cherry Blossom',
                'deep_pond'      => 'Deep Pond',
            ],
        ],

        'retro_digital' => [
            'label'        => 'Cozy Digital / Retro',
            'supporter_only' => true,
            'avatars' => [
                'pixel_cat'         => 'Pixel Cat',
                'retro_controller'  => 'Retro Controller',
                'old_computer'      => 'Old Computer',
                'tiny_robot'        => 'Tiny Robot',
                'floppy_disk'       => 'Floppy Disk',
                'pixel_frog'        => 'Pixel Frog',
                'loading_screen'    => 'Loading Screen',
                'terminal_window'   => 'Terminal Window',
                'retro_cursor'      => 'Retro Cursor',
                'pixel_rain'        => 'Pixel Rain',
                'handheld_console'  => 'Handheld Console',
                'pixel_stars'       => 'Pixel Stars',
                'old_internet'      => 'Old Internet',
                'crt_tv'            => 'CRT TV',
                'midi_keyboard'     => 'MIDI Keyboard',
                'pixel_dog'         => 'Pixel Dog',
                'retro_phone'       => 'Retro Phone',
                'pixel_tree'        => 'Pixel Tree',
                'game_cartridge'    => 'Game Cartridge',
                'pixel_house'       => 'Pixel House',
                'pixel_bird'        => 'Pixel Bird',
                'retro_calculator'  => 'Retro Calculator',
                'pixel_plant'       => 'Pixel Plant',
                'dial_up'           => 'Dial-Up',
                'disk_pack'         => 'Disk Pack',
            ],
        ],

        'mood_vibe' => [
            'label'   => 'Mood & Vibe',
            'avatars' => [
                'sleepy_ghost'     => 'Sleepy Ghost',
                'quiet_fox'        => 'Quiet Fox',
                'cozy_bear'        => 'Cozy Bear',
                'cloud_person'     => 'Cloud Person',
                'tiny_dragon'      => 'Tiny Dragon',
                'sleepy_raccoon'   => 'Sleepy Raccoon',
                'listener_frog'    => 'Listener Frog',
                'blanket_ghost'    => 'Blanket Ghost',
                'calm_rabbit'      => 'Calm Rabbit',
                'floating_spirit'  => 'Floating Spirit',
                'lantern_creature' => 'Lantern Creature',
                'moth_friend'      => 'Moth Friend',
                'sleepy_cat'       => 'Sleepy Cat',
                'soft_deer'        => 'Soft Deer',
                'cozy_hedgehog'    => 'Cozy Hedgehog',
                'rain_frog'        => 'Rain Frog',
                'midnight_owl'     => 'Midnight Owl',
                'cloud_sheep'      => 'Cloud Sheep',
                'tiny_witch'       => 'Tiny Witch',
                'mushroom_spirit'  => 'Mushroom Spirit',
                'sleepy_bear_cub'  => 'Sleepy Bear Cub',
                'jellyfish'        => 'Jellyfish',
                'warm_duck'        => 'Warm Duck',
                'glow_bunny'       => 'Glow Bunny',
                'soft_penguin'     => 'Soft Penguin',
                'cozy_sloth'       => 'Cozy Sloth',
                'tiny_snail'       => 'Tiny Snail',
                'star_mouse'       => 'Star Mouse',
                'fog_creature'     => 'Fog Creature',
                'dusk_bird'        => 'Dusk Bird',
            ],
        ],

        'minimal' => [
            'label'   => 'Minimal',
            'avatars' => [
                'soft_gradient'   => 'Soft Gradient',
                'abstract_waves'  => 'Abstract Waves',
                'constellation'   => 'Constellation',
                'geometric'       => 'Geometric',
                'radial_bloom'    => 'Radial Bloom',
                'soft_rings'      => 'Soft Rings',
                'scattered_dots'  => 'Scattered Dots',
                'gentle_arc'      => 'Gentle Arc',
                'diamond_grid'    => 'Diamond Grid',
                'ink_wash'        => 'Ink Wash',
                'soft_haze'       => 'Soft Haze',
                'color_blocks'    => 'Color Blocks',
                'parallel_lines'  => 'Parallel Lines',
                'soft_spiral'     => 'Soft Spiral',
                'moon_phases'     => 'Moon Phases',
                'simple_mountain' => 'Simple Mountain',
                'horizon_line'    => 'Horizon Line',
                'rain_pattern'    => 'Rain Pattern',
                'cross_hatch'     => 'Cross Hatch',
                'soft_vortex'     => 'Soft Vortex',
            ],
        ],

        'seasonal' => [
            'label'          => 'Seasonal',
            'supporter_only' => true,
            'avatars' => [
                'autumn_lantern'   => 'Autumn Lantern',
                'winter_lamp'      => 'Winter Lamp',
                'rainy_autumn'     => 'Rainy Autumn',
                'spring_flowers'   => 'Spring Flowers',
                'summer_night'     => 'Summer Night',
                'snowy_cabin'      => 'Snowy Cabin',
                'harvest_moon'     => 'Harvest Moon',
                'frozen_lake'      => 'Frozen Lake',
                'cherry_blossom'   => 'Cherry Blossom',
                'firework_distant' => 'Distant Firework',
                'pumpkin_small'    => 'Little Pumpkin',
                'snowman_simple'   => 'Simple Snowman',
                'spring_bird'      => 'Spring Bird',
                'summer_beach'     => 'Summer Beach',
                'winter_deer'      => 'Winter Deer',
            ],
        ],

    ],

];
